INSERT INTO Subjects VALUES
-- C1 S1
(NULL, "Cálculo", "primero"),
(NULL, "Informática General", "primero"),
(NULL, "Introducción a la Programación", "primero"),
(NULL, "Matemática Discreta", "primero"),
(NULL, "Sistemas Digitales", "primero"),
-- C1 S2
(NULL, "Estadística", "primero"),
(NULL, "Álgebra Lineal", "primero"),
(NULL, "FFEI", "primero"),
(NULL, "Fundamentos de EStructura de Computadores", "primero"),
(NULL, "Metodología de la Programación", "primero"),
-- C2 S1
(NULL, "Análisis de Algoritmos y Estructura de Datos", "segundo"),
(NULL, "Arquitectura de Computadores", "segundo"),
(NULL, "Organización y Gestión de Empresas", "segundo"),
(NULL, "Redes de Computadores", "segundo"),
(NULL, "Sistemas Operativos", "segundo"),
-- C2 S1
(NULL, "Bases de Datos", "segundo"),
(NULL, "Estructura de Datos no Lineales", "segundo"),
(NULL, "Ingeniería del Software", "segundo"),
(NULL, "Programación Orientada a Objetos", "segundo"),
(NULL, "Sistemas Distribuidos", "segundo"),
-- C3
(NULL, "Diseño de Algoritmos", "tercero"),
(NULL, "Inteligencia Artificial", "tercero"),
(NULL, "Programación Concurrente y de Tiempo Real", "tercero"),
(NULL, "Proyectos Informáticos", "tercero"),
(NULL, "Seguridad en los Sistemas Informáticos", "tercero"),
(NULL, "Modelos de Computación", "tercero"),
(NULL, "Reconocimiento de Patrones", "tercero"),
(NULL, "Sistemas Inteligentes", "tercero"),
(NULL, "Teoría de Automátas y Lenguajes Formales", "tercero"),
(NULL, "Diseño Basado en Microprocesadores", "tercero"),
(NULL, "Diseño de Computadores Empotrados", "tercero"),
(NULL, "Diseño de Redes de Computadores", "tercero"),
(NULL, "Técnicas de Diseño de Computadores", "tercero"),
(NULL, "IISS", "tercero"),
(NULL, "Ingeniería de Requisitos", "tercero"),
(NULL, "Verificación y Validación del Software", "tercero"),
(NULL, "Desarrollo de Sistemas Hipermedia", "tercero"),
(NULL, "Programación en Internet", "tercero"),
(NULL, "Sistemas de Información en la Empresa", "tercero"),
(NULL, "Tecnologías Avanzadas de Bases de Datos", "tercero"),
(NULL, "Administración de Servidores", "tercero"),
(NULL, "Interacción Persona-Ordenador", "tercero"),
(NULL, "Interconexión de Redes", "tercero"),
(NULL, "Programación Web", "tercero"),
-- C4
(NULL, "Aprendizaje Computacional", "cuarto"),
(NULL, "Complejidad Computacional", "cuarto"),
(NULL, "Percepción", "cuarto"),
(NULL, "Procesadores de Lenguaje", "cuarto"),
(NULL, "ASRC", "cuarto"),
(NULL, "ACPD", "cuarto"),
(NULL, "DAAC", "cuarto"),
(NULL, "Programación Paralela y Distribuida", "cuarto"),
(NULL, "Calidad del Software", "cuarto"),
(NULL, "Dirección y Gestión de Proyectos Software", "cuarto"),
(NULL, "Evolución del Software", "cuarto"),
(NULL, "Metodologías y Procesos Software", "cuarto"),
(NULL, "Administración de Base de Datos", "cuarto"),
(NULL, "Ingeniería de Sistemas de la Información", "cuarto"),
(NULL, "Recuperación de la Información", "cuarto"),
(NULL, "Tecnologías de Inteligencia de Negocios", "cuarto"),
(NULL, "Calidad en los Sistemas Informáticos", "cuarto"),
(NULL, "Ingeniería Web", "cuarto"),
(NULL, "Internet y Negocio Electrónico", "cuarto"),
(NULL, "Virtualización de Sistemas", "cuarto"),
(NULL, "Trabajo Fin de Grado", "cuarto");